accounts/urls.py
"""Urls for account related things"""
from django.urls import path, include
from . import views

app_name='accounts'
urlpatterns = [
    #include default auth urls
    path('', include('django.contrib.auth.urls')),
    #Registration page
    path('register/',views.register, name='register'),    
]

bounties/urls.py
"""Defines urls for encoded"""

from django.urls import path

from . import views

app_name='bounties'
urlpatterns = [
    #home page
    path('', views.index, name='index'),
    
    #Subjects
    path('subjects/', views.subjects, name='subjects'),
    #Topics
    path('subjects/<int:subject_id>/', views.subject, name='subject'),
   
    #Bounties
    path('topics/<int:topic_id>/', views.topic, name='topic'),    
    path('topic/<int:topic_id>/<int:bounty_id>', views.bounty, name='bounty'),
    path('new_bounty/<int:topic_id>/', views.new_bounty, name='new_bounty'),
    path('edit_bounty/<int:bounty_id>/', views.edit_bounty, name='edit_bounty'),

    #comments
    path('add_comment/<int:topic_id>/<int:bounty_id>/', views.new_comment, name='new_comment'),
    path('edit_comment/<int:bounty_id>/<int:comment_id>/', views.edit_comment, name='edit_comment'),

]

encoded/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bounties.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

bounties/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Subject(models.Model):
    """A subject the user is studying"""
    name=models.CharField(max_length=50)
    owner=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Returns string representation of name"""
        return self.name
    
class Topic(models.Model):
    """A topic the user is learning"""
    owner=models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=200)
    subject=models.ForeignKey(Subject, on_delete=models.CASCADE)
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Bounty(models.Model):
    """A topic a student needs help with"""
    owner=models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=200)
    subject=models.ForeignKey(Subject, on_delete=models.CASCADE)
    topic=models.ForeignKey(Topic, on_delete=models.CASCADE)
    date_added=models.DateTimeField(auto_now_add=True)
    text=models.TextField(default="Nedokoncana objava")

    class Meta:
        verbose_name_plural = 'bounties'

    def __str__(self):
        return self.name

class Comment(models.Model):
    """The comment section on a bounty"""
    owner=models.ForeignKey(User, on_delete=models.CASCADE)
    bounty=models.ForeignKey(Bounty, on_delete=models.CASCADE)
    date_added=models.DateTimeField(auto_now_add=True)
    text=models.TextField(default="Nedokoncana objava")

    def __str__(self):
        return self.text

bounties/forms.py
from django import forms

from .models import Bounty, Comment

class BountyForm(forms.ModelForm):
    class Meta:
        model=Bounty
        fields = ['name', 'text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text':forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register the user"""
    if request.method != 'POST':
        # display a blank registration form
        form=UserCreationForm()
    else:
        form=UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            #log in and redirect to home page
            login(request, new_user)
            return redirect('bounties:index')
        
    #Display a blank or invalid form
    context={'form': form}
    return render(request, 'registration/register.html', context)

bounties/views.py
from django.shortcuts import render, redirect
from .models import Subject, Topic, Bounty, Comment
from. forms import BountyForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
def index(request):
    """Home page for encoded"""
    return render(request, 'bounties/index.html')

def subjects(request):
    """Returns list of all subjects"""
    subjects=Subject.objects.order_by('name')
    context={'subjects': subjects}
    return render(request, 'bounties/subjects.html', context)

def subject(request, subject_id):
    """return page for a specific subject"""
    subject=Subject.objects.get(id=subject_id)
    topics=subject.topic_set.all()
    context = {'subject': subject, 'topics': topics}
    return render(request, 'bounties/subject.html', context)

def topic(request, topic_id):
    """Return page containing bounties for current topic"""
    topic=Topic.objects.get(id=topic_id)
    bounties=topic.bounty_set.order_by('-date_added')
    context={'topic': topic, 'bounties': bounties}
    return render(request, 'bounties/topic.html', context)

def bounty(request, topic_id, bounty_id):
    """Return page for specific bounty"""
    topic=Topic.objects.get(id=topic_id)
    bounty=topic.bounty_set.get(id=bounty_id)
    comments=bounty.comment_set.all()
    context={'bounty': bounty, 'comments': comments, 'topic_id': topic_id}
    return render(request, 'bounties/bounty.html', context)

@login_required
def new_bounty(request, topic_id):
    """Returns page for creating a new bounty"""
    topic=Topic.objects.get(id=topic_id)
    subject=topic.subject

    if request.method != 'POST':
        #No data submitted; create blank form.
        form=BountyForm()
    else:
        #Post data submitted; process data.
        form=BountyForm(data=request.POST)
        if form.is_valid():
            new_bounty=form.save(commit=False)
            new_bounty.topic = topic
            new_bounty.subject = subject
            new_bounty.owner = request.user
            new_bounty.save()
            return redirect('bounties:topic', topic_id=topic_id)
        
    #Display blank or invalid form
    context = {'topic': topic, 'form': form}
    return render(request, 'bounties/new_bounty.html', context)

@login_required
def edit_bounty(request, bounty_id):
    """Edit an existing bounty"""
    bounty=Bounty.objects.get(id=bounty_id)
    if bounty.owner != request.user:
        raise Http404
    topic=bounty.topic

    if request.method != 'POST':
        # initial reqest
        form = BountyForm(instance=bounty)
    else:
        # post data submitted
        form=BountyForm(instance=bounty, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('bounties:topic', topic_id=topic.id)
        
    context = {'bounty': bounty, 'topic': topic, 'form': form}
    return render(request, 'bounties/edit_bounty.html', context)

@login_required
def new_comment(request, topic_id, bounty_id):
    """Returns comment creation page"""
    bounty=Bounty.objects.get(id=bounty_id)

    if request.method != 'POST':
        #no post data, make empty form
        form=CommentForm()
    else:
        form=CommentForm(data=request.POST)
        if form.is_valid():
            new_comment=form.save(commit=False)
            new_comment.owner = request.user
            new_comment.bounty=bounty
            new_comment.save()
            return redirect('bounties:bounty', topic_id=topic_id, bounty_id=bounty_id)
    
    context={'form': form, 'bounty': bounty, 'topic_id': topic_id}
    
    #Display blank / invalid form
    return render(request, 'bounties/new_comment.html', context)

@login_required
def edit_comment(request, bounty_id, comment_id):
    """edit an existing comment"""
    comment=Comment.objects.get(id=comment_id)
    bounty=Bounty.objects.get(id=bounty_id)
    if comment.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        form = CommentForm(instance=comment)
    else:
        form=CommentForm(instance=comment, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('bounties:bounty', topic_id=bounty.topic.id, bounty_id=bounty.id)
        
    context = {'comment': comment, 'bounty': bounty, 'form': form}
    return render(request, 'bounties/edit_comment.html', context)
    

bounties/templates/bounties/base.html
<!DOCTYPE html>
<html lang="si">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Encoded</title>

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>
<body>
  
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
       <a class="navbar-brand" href="{% url 'bounties:index' %}">
        Encoded</a>

       <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

       <div class="collapse navbar-collapse" id="navbarCollapse">
         <ul class="navbar-nav me-auto mb-2 mb-md-0">
           <li class="nav-item">
             <a class="nav-link" href="{% url 'bounties:subjects' %}">
              Predmeti</a></li>
        </ul> <!-- End of links on left side of navbar -->

        <!-- Account-related links -->
         <ul class="navbar-nav ms-auto mb-2 mb-md-0">

             {% if user.is_authenticated %}
              <li class="nav-item">
                 <span class="navbar-text me-2">Hello, {{ user.username }}.
                  </span></li>
             {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register' %}">
                    Registriraj se</a></li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">
                    Prijavi se</a></li>
            {% endif %}
  
          </ul> <!-- End of account-related links -->

          {% if user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method='post'>
            {% csrf_token %}
             <button name='submit' class='btn btn-outline-secondary btn-sm'>
                Odjavi se</button>
          </form>
        {% endif %}

      </div> <!-- Closes collapsible parts of navbar -->

    </div> <!-- Closes navbar's container -->
  </nav> <!-- End of navbar -->

  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>  
  </main>

  
</body>
</html>

bounties/templates/bounties/bounty.html
{% extends 'bounties/base.html' %}

{% block content %}

<h2>{{ bounty.name }}</h2>
<p>{{ bounty.text|linebreaks }}</p>
<p>
    {% if bounty.owner == request.user %}
        <a href="{% url 'bounties:edit_bounty' bounty.id %}">
            Uredi objavo <br/>
        </a>
    {% endif %}
</p>
<br/>
<br/>
<hr/>
<a href="{% url 'bounties:new_comment' topic_id bounty.id %}">Dodaj komentar</a> <br>
<ul>
  <br>
    {% for comment in comments %}
      <li>{{ comment.text|linebreaks }}</li>
      {% if comment.owner == request.user %}
        <a href="{% url 'bounties:edit_comment' bounty.id comment.id %}">Uredi komentar</a>
      {% endif %}
      <hr>
    {% empty %}
      <li>Nihče še ni komentiral</li>
    {% endfor %}
</ul>

{% endblock content %}

bounties/templates/bounties/edit_bounty.html
{% extends 'bounties/base.html' %}

{% block content %}

<p><a href="{% url 'bounties:topic' topic.id %}">{{ topic }}</a></p>

<p>Uredi tekst:</p>

<form action="{% url 'bounties:edit_bounty' bounty.id %}" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Shrani Spremembe</button>
</form>

{% endblock content %}

bounties/templates/bounties/edit_comment.html
{% extends 'bounties/base.html' %}

{% block content %}

<p><a href="{% url 'bounties:bounty' bounty.topic.id bounty.id %}">{{ bounty }}</a></p>

<p>Uredi tekst:</p>

<form action="{% url 'bounties:edit_comment' bounty.id comment.id%}" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Shrani Spremembe</button>
</form>

{% endblock content %}

bounties/templates/bounties/index.html
{% extends 'bounties/base.html' %}
{% block page_header %}
   <div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
       <h1 class="display-3">Odpravi vprašanja pri učenju</h1>

       <p class="lead">
        Zastavi vprašanja za katerokoli temo, ki te zanima in nekdo
        ti bo odgovoril. Prav tako lahko poiščeš odgovore na vprašanja,
        ki jih je nekdo že zastavil ali celo odgovoriš na vprašanja,
        ki še nimajo odgovora. Cilj je imeti stran, ki bo imela odgovore
        na večino vprašanj, ki jih imajo učenci.
       </p>

       <a class="btn btn-primary btn-lg mt-1"
        href="{% url 'accounts:register' %}">Registriraj se &raquo;</a>
    </div>
  </div>
{% endblock page_header %}

bounties/templates/bounties/new_bounty.html
{% extends 'bounties/base.html' %}

{% block content %}

<p><a href="{% url 'bounties:topic' topic.id %}">{{ topic }}</a></p>

<p>Zastavi novo vprašanje:</p>
<form action="{% url 'bounties:new_bounty' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Post bounty</button>
</form>


{% endblock content %}

bounties/templates/bounties/new_comment.html
{% extends 'bounties/base.html' %}

{% block content %}

<p><a href="{% url 'bounties:bounty' topic_id bounty.id %}">{{ bounty.name }}</a></p>

<p>Dodaj komentar:</p>
<form action="{% url 'bounties:new_comment' topic_id bounty.id %}" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Objavi komentar</button>
</form>


{% endblock content %}

bounties/templates/bounties/subject.html
{% extends 'bounties/base.html' %}

{% block page_header %}
<h1>Predmet: {{ subject.name }}</h1>
{% endblock page_header %}

{% block content %}

<p>Teme: </p>

<ul class="list-group border-bottom pb-2 mb-4">
    {% for topic in topics %}
      <li class="list-group-item border-0">
        <a href="{% url 'bounties:topic' topic.id %}">{{ topic.name }}</a>
      </li>
    {% empty %}
      <li class="list-group-item border-0">Trenutno ni še nobene teme za ta predmet</li>
    {% endfor %}
</ul>

{% endblock content %}

bounties/templates/bounties/subjects.html
{% extends 'bounties/base.html'  %}

{% block page_header %}
<h1>Predmeti:</h1>
{% endblock page_header %}
{% block content %}


<ul class="list-group border-bottom pb-2 mb-4">
    {% for subject in subjects %}
      <li class="list-group-item border-0">
        <a href="{% url 'bounties:subject' subject.id %}">{{ subject.name }}</a>
      </li>
    {% empty %}
      <li class="list-group-item border-0">Trenutno še ni nobenega predmeta</li>
    {% endfor %}
</ul>

{% endblock content %}

bounties/templates/bounties/topic.html
{% extends 'bounties/base.html' %}

{% block page_header %}
<h1>Tema: {{ topic.name }}</h1>
{% endblock page_header %}

{% block content %}

<p>Vprašanja: </p>
<p>
  <a href="{% url 'bounties:new_bounty' topic.id %}">Dodaj novo vprašanje</a>
</p>
  {% for bounty in bounties %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ bounty.date_added|date:'M d, Y H:i' }}</p>
        <a href="{% url 'bounties:bounty' topic.id bounty.id %}">{{ bounty.name }}</a>
      </h4>
      <div class="card-body">{{ bounty.text }}</div>
    </div>
  {% empty %}
    <p>Nihče še ni zastavil vprašanja za to temo.</p>
  {% endfor %}


{% endblock content %}